apiVersion: v1
kind: Pod
metadata:
  name: trening-backend-pod
  labels:
    component: trening-backend
spec:
  containers:
    - name: trening-backend
      image: trening-backend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
