apiVersion: v1
kind: Service
metadata:
  name: trening-backend-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31515
  selector:
    component: trening-backend
